"""
ailogproc - 日志到Excel匹配工具
将结构化日志文件自动填充到Excel模板中的工程化工具
"""

from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

with open("requirements.txt", "r", encoding="utf-8") as fh:
    requirements = [line.strip() for line in fh if line.strip() and not line.startswith("#")]

setup(
    name="ailogproc",
    version="5.0.0",
    author="Generated by Claude",
    description="将结构化日志文件自动填充到Excel模板中的工程化工具",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/ailogproc",
    packages=find_packages(exclude=["tests", "examples", "docs"]),
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=requirements,
    entry_points={
        "console_scripts": [
            "ailogproc=main:main",
        ],
    },
    include_package_data=True,
    package_data={
        "config": ["*.yaml", "*.yml"],
        "src.utils": ["*.yaml", "*.yml"],
        "src.plugins": ["**/config.yaml"],
    },
)
