"""
常量定义 - 避免魔法数字
"""

# 文件大小相关
BYTES_PER_KB = 1024
BYTES_PER_MB = BYTES_PER_KB * 1024
MAX_LOG_FILE_SIZE_MB = 100

# 时间相关
SECONDS_PER_MINUTE = 60
MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24
DAYS_IN_MONTH_MAX = 31
DAYS_IN_FEBRUARY_LEAP = 29
DAYS_IN_FEBRUARY = 28

# 字节操作相关
BITS_PER_BYTE = 8
BYTES_IN_UINT16 = 2
BYTES_IN_UINT32 = 4

# 16进制相关
HEX_CHARS_PER_BYTE = 2
HEX_BASE = 16

# 文件权限相关
DIR_MODE_DEFAULT = 0o755
DIR_MODE_READONLY = 0o444
DIR_MODE_PRIVATE = 0o700

# 日志相关
DEFAULT_LOG_FILE_BACKUP_COUNT = 5
DEFAULT_LOG_MAX_BYTES = BYTES_PER_MB

# Excel相关
MAX_EXCEL_ROWS = 1048576  # Excel最大行数
MAX_EXCEL_COLUMNS = 16384  # Excel最大列数
DEFAULT_TABLE_SCAN_ROWS = 20

# 分隔符长度
SEPARATOR_LENGTH_SHORT = 60
SEPARATOR_LENGTH_MEDIUM = 70
SEPARATOR_LENGTH_LONG = 80
